---
- name: install-redhat | Install any necessary dependencies [RedHat/CentOS]
  ansible.builtin.dnf:
    name: "{{ telegraf_dep_pkgs }}"
    state: present

- name: install-redhat | Add InfluxData repository file [RHEL/CentOS]
  ansible.builtin.yum_repository:
    baseurl: "{{ telegraf_influxdata_base_url }}/rhel/$releasever/$basearch/stable"
    name: influxdb
    description: InfluxDB Repository
    gpgkey: "{{ telegraf_influxdata_base_url }}/influxdata-archive_compat.key"
  when: telegraf_rpm_pkg_url is not defined or telegraf_rpm_pkg_url == None

- name: install-redhat | verify influxdata key
  ansible.builtin.rpm_key:
    state: present
    #key: "{{ telegraf_influxdata_base_url }}/influxdata-archive.key"
    key: "{{ telegraf_influxdata_base_url }}/influxdata-archive_compat.key"

- name: install-redhat | Install Telegraf packages [RHEL/CentOS]
  ansible.builtin.dnf:
    name: telegraf
    state: latest
    update_cache: true
    update_only: false # true
  register: telegraf_pkg_install
  until: telegraf_pkg_install is not failed
  when: telegraf_rpm_pkg_url is not defined or telegraf_rpm_pkg_url == None
  notify: Restart Telegraf

- name: install-redhat | Install downloaded Telegraf package [RHEL/CentOS]
  ansible.builtin.dnf:
    name: "{{ telegraf_rpm_pkg_url }}"
    state: present
    allow_downgrade: true
    disable_gpg_check: true
  register: telegraf_rpm_install
  until: telegraf_rpm_install is not failed
  when: telegraf_rpm_pkg_url is defined and telegraf_rpm_pkg_url != None
  notify: Restart Telegraf
